# Generated by Django 3.0.4 on 2020-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0005_ipltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IplTestView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=255)),
                ('winner_count', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'ipl_testview',
                'managed': False,
            },
        ),
    ]
