# Generated by Django 3.0.4 on 2020-03-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0006_ipltestview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IplTestView',
        ),
    ]
