# Generated by Django 3.0.4 on 2020-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0008_ipltestview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOfMatchView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_of_match', models.CharField(max_length=255)),
                ('player_of_match_count', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'player_of_match_view',
                'managed': False,
            },
        ),
    ]
