# Generated by Django 3.0.4 on 2020-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0010_teamwins_yearview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teamwins_yearView',
        ),
    ]
