# Generated by Django 3.0.4 on 2020-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0011_delete_teamwins_yearview'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamwins_yearView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('winner_count', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'teamwins_year',
                'managed': False,
            },
        ),
    ]
