# Generated by Django 3.0.4 on 2020-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0013_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IplFinalView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=255)),
                ('champion_count', models.DecimalField(decimal_places=0, max_digits=19)),
            ],
            options={
                'db_table': 'iplfinal_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='topbatsmanview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('PLAYER_NAME', models.CharField(max_length=255)),
                ('MATCHES', models.DecimalField(decimal_places=0, max_digits=19)),
                ('INNS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('NOTOUT', models.DecimalField(decimal_places=0, max_digits=19)),
                ('RUNS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('HIGEST_SCORE', models.DecimalField(decimal_places=0, max_digits=19)),
                ('AVERAGE', models.DecimalField(decimal_places=2, max_digits=19)),
                ('BF', models.DecimalField(decimal_places=0, max_digits=19)),
                ('STRIKERATE', models.DecimalField(decimal_places=2, max_digits=19)),
                ('HUNDREDS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('FIFTIES', models.DecimalField(decimal_places=0, max_digits=19)),
                ('FOURS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('SIXES', models.DecimalField(decimal_places=0, max_digits=19)),
            ],
            options={
                'db_table': 'topbatsman_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='topbowlersview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('PLAYER_NAME', models.CharField(max_length=255)),
                ('MATCHES', models.DecimalField(decimal_places=0, max_digits=19)),
                ('INNS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('OVER', models.DecimalField(decimal_places=0, max_digits=19)),
                ('RUNS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('WICKETS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('BBI', models.DecimalField(decimal_places=2, max_digits=19)),
                ('AVERAGE', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ECONOMY', models.DecimalField(decimal_places=2, max_digits=19)),
                ('STRIKERATE', models.DecimalField(decimal_places=2, max_digits=19)),
                ('FOUR_WIKETS', models.DecimalField(decimal_places=0, max_digits=19)),
                ('FIVE_WICKETS', models.DecimalField(decimal_places=0, max_digits=19)),
            ],
            options={
                'db_table': 'topbowlers_view',
                'managed': False,
            },
        ),
    ]
