# Generated by Django 3.0.4 on 2020-05-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0015_deliveries_history_inningscore_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
