# Generated by Django 3.0.4 on 2020-09-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipltest', '0017_itenary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_ID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipl_matchid',
                'managed': True,
            },
        ),
    ]
